package org.ohmyopensource.ohmyuniversity.core.domain.entity;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.PostLoad;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;
import jakarta.persistence.Transient;
import jakarta.validation.constraints.NotBlank;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import org.springframework.data.domain.Persistable;

/**
 * Core identity entity representing a stable OhMyUniversity user.
 *
 * <p>This entity is NOT a replica of Cineca or university-specific data. It represents a unified
 * person identity across multiple universities.
 *
 * <p>The main identifier is the Italian fiscal code (codice fiscale), which acts as the
 * cross-university linking key.
 *
 * <p>Responsibilities:
 * - Provide a stable internal user identity - Link multiple UniversityConnection records - Track
 * authentication metadata (creation, last login)
 *
 * <p>No academic or career data is stored in this entity. All student-related information is
 * retrieved dynamically from Cineca APIs and optionally cached externally (e.g., Redis).
 */
@Entity
@Table(name = "omu_user")
public class OmuUser implements Persistable<UUID> {

  /**
   * List of university-specific connections associated with this user.
   *
   * <p>Represents the relationship between the global user identity and multiple Cineca/university
   * accounts.
   */
  @OneToMany(mappedBy = "user", cascade = CascadeType.ALL,
      fetch = FetchType.LAZY, orphanRemoval = true)
  private final List<UniversityConnection> universityConnections = new ArrayList<>();

  /**
   * Unique internal identifier (UUID).
   *
   * <p>Unlike a typical entity, this is never generated by Hibernate — the core
   * service only ever creates a local shadow of a user whose identity already exists, with the
   * exact UUID the auth service assigned. Hence no {@code @GeneratedValue}: mixing it with a
   * manually-assigned id caused Hibernate to intermittently treat brand-new instances as "detached"
   * during persist.
   */
  @Id
  @Column(name = "id", updatable = false, nullable = false, columnDefinition = "uuid")
  private UUID id;
  /**
   * Italian fiscal code used as cross-university unique identifier.
   */
  @NotBlank
  @Column(name = "codice_fiscale", nullable = false, unique = true, length = 16)
  private String codiceFiscale;
  /**
   * Primary email address of the user in the OhMyUniversity system.
   */
  @Column(name = "email_primaria")
  private String emailPrimaria;
  /**
   * Timestamp of user creation.
   */
  @Column(name = "created_at", nullable = false, updatable = false)
  private Instant createdAt;
  /**
   * Timestamp of last successful login.
   */
  @Column(name = "last_login_at")
  private Instant lastLoginAt;

  /**
   * Tracks whether this instance is a brand-new, not-yet-persisted entity.
   *
   * <p>Needed because {@code id} is assigned manually by callers such as
   * {@code UserAuthenticatedEventListener} (it must match the UUID the auth service already
   * generated for this user), not database-generated — without this, Spring Data JPA sees a
   * non-null id and assumes the row already exists, issuing an UPDATE instead of an INSERT for new
   * users and failing with "Row was already updated or deleted by another transaction".
   */
  @Transient
  private boolean isNew = true;

  // ============ Override Methods ============

  @Override
  public boolean isNew() {
    return isNew;
  }

  // ============ Getters | Setters | Bool ============

  public UUID getId() {
    return id;
  }

  public void setId(UUID id) {
    this.id = id;
  }

  public String getCodiceFiscale() {
    return codiceFiscale;
  }

  public void setCodiceFiscale(String codiceFiscale) {
    this.codiceFiscale = codiceFiscale;
  }

  public String getEmailPrimaria() {
    return emailPrimaria;
  }

  public void setEmailPrimaria(String emailPrimaria) {
    this.emailPrimaria = emailPrimaria;
  }

  public Instant getCreatedAt() {
    return createdAt;
  }

  public Instant getLastLoginAt() {
    return lastLoginAt;
  }

  public void setLastLoginAt(Instant lastLoginAt) {
    this.lastLoginAt = lastLoginAt;
  }

  public List<UniversityConnection> getUniversityConnections() {
    return universityConnections;
  }

  // ============ Class Methods ============

  /**
   * Sets the creation timestamp and marks this instance as no longer new, right before its first
   * insert.
   */
  @PrePersist
  void onCreate() {
    createdAt = Instant.now();
    this.isNew = false;
  }

  /**
   * Marks this instance as no longer new when an existing row is loaded from the database.
   */
  @PostLoad
  void onLoad() {
    this.isNew = false;
  }
}