spring:
  profiles:
    default: dev
  application:
    name: ohmyuniversity-core
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

# JWT configuration
omu:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: ${JWT_EXPIRATION_MS:3600000}       # 60 minutes default

  # List of Registered universities
  universities:
    UNIMOL:
      name: Università degli Studi del Molise
      base-url: https://unimol.esse3.cineca.it/e3rest/api
      esse3-portal-url: https://unimol.esse3.cineca.it/Start.do
      moodle-url: https://learn.unimol.it
      library-url: https://opac.regione.molise.it/SebinaOpac/.do?sysb=universita