spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
      # autoconfigure:
    #exclude:
    # - org.springframework.boot.autoconfigure.security.oauth2.resource.servlet.OAuth2ResourceServerAutoConfiguration

management:
  otlp:
    metrics:
      export:
        enabled: false
  tracing:
    export:
      enabled: false

omu:
  jwt:
    secret: test_secret_key_must_be_at_least_32_chars_long
    expiration-ms: 900000
  universities:
    UNIMOL:
      name: Università degli Studi del Molise
      base-url: https://unimol.esse3.cineca.it/e3rest/api

logging:
  level:
    org.ohmyopensource: DEBUG
    org.springframework.security: DEBUG
    org.testcontainers: INFO
    org.flywaydb: DEBUG